"""Values interpolated into a document that is later PARSED, not serialised.

This is the same anti-pattern in two places:

  * installer/autoinstall.yaml.template hand-quoted the password hash and the
    SSH authorized-key with a bare, hand-typed single quote. A crypt(3) hash
    happens to contain no apostrophe, so it was safe by luck - but an SSH
    key's comment field routinely does (``... jake's laptop``), and a
    hand-quoted apostrophe inside a single-quoted YAML scalar produces an
    answer file that is not YAML. The unattended install then fails
    somewhere nobody will ever see it.

  * installer/provision.sh interpolates ``${MEDIA_ROOT}`` bare into the first
    config.yaml it writes, twice. A value with a ``#`` in it truncates at the
    comment and the box builds its lineup from the wrong folder; one with a
    ``:`` makes the document unparseable, which on a fresh image is a unit
    that never starts.

Both are fixed the same way installer/lib/render_autoinstall.py already fixes
the wifi SSID and password: quote the value properly (``yaml_str()``), or -
where that is not practical inside a bash heredoc - validate it and refuse to
write anything unsafe.

Nothing here touches this machine's real /etc, and nothing here runs a real
installer: render_autoinstall.py is invoked exactly as
tests/test_installer_boot.py invokes it (a subprocess against a throwaway
output file), and the provision.sh config-writing step is exercised by
extracting its own current source lines - not a copy of them - into a
throwaway sandbox, so what is proved true is true of the real file.
"""

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

yaml = pytest.importorskip("yaml")

ROOT = Path(__file__).resolve().parent.parent
INSTALLER = ROOT / "installer"
TEMPLATE = INSTALLER / "autoinstall.yaml.template"
RENDER = INSTALLER / "lib" / "render_autoinstall.py"
PROVISION = INSTALLER / "provision.sh"


def _clean_env():
    env = dict(os.environ)
    env.update({
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_SYSTEM": os.devnull,
        "PATH": str(Path(sys.executable).parent) + os.pathsep + os.environ.get("PATH", ""),
    })
    return env


# ==========================================================================
# 1. The SSH key and password hash, rendered into the real template.
# ==========================================================================
def _render(tmp_path, *, key_text, password="a-long-enough-password"):
    key = tmp_path / "id_test.pub"
    key.write_text(key_text, encoding="utf-8")
    out = tmp_path / "autoinstall.yaml"
    env = _clean_env()
    env.update({"RETROBOX_PASSWORD": password, "RETROBOX_SSH_KEY": str(key)})
    result = subprocess.run(
        [sys.executable, str(RENDER), str(TEMPLATE), str(out)],
        env=env, capture_output=True, text=True, timeout=120,
    )
    return result, (out.read_text(encoding="utf-8") if out.exists() else None)


def test_an_ssh_key_whose_comment_has_an_apostrophe_still_renders_valid_yaml(tmp_path):
    # The exact shape of key that broke this: ssh-keygen's default comment is
    # "user@host", and a great many people's account name has an apostrophe
    # in it.
    key_text = (
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH00000000000000000000000000"
        "00000000000000 jake's laptop\n"
    )
    result, text = _render(tmp_path, key_text=key_text)
    assert result.returncode == 0, result.stderr
    document = yaml.safe_load(text)
    keys = document["autoinstall"]["ssh"]["authorized-keys"]
    assert keys == [key_text.strip()]


def test_an_ssh_key_comment_with_a_double_quote_and_hash_still_renders_valid_yaml(tmp_path):
    key_text = (
        'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH00000000000000000000000000'
        '00000000000000 "work" box #3\n'
    )
    result, text = _render(tmp_path, key_text=key_text)
    assert result.returncode == 0, result.stderr
    document = yaml.safe_load(text)
    keys = document["autoinstall"]["ssh"]["authorized-keys"]
    assert keys == [key_text.strip()]


def test_the_password_hash_still_renders_as_a_single_correctly_quoted_scalar(tmp_path):
    # The hash is generated by the renderer itself (sha512_crypt), so it is
    # never attacker-controlled - this just proves the new quoting path
    # (yaml_str, not a hand-typed quote in the template) did not break the
    # ordinary case, which is full of '$'.
    key_text = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH0 plain\n"
    result, text = _render(tmp_path, key_text=key_text)
    assert result.returncode == 0, result.stderr
    document = yaml.safe_load(text)
    password = document["autoinstall"]["identity"]["password"]
    assert password.startswith("$6$")
    # Exactly one scalar, not a value that got split across a YAML structure
    # by an unescaped '$' or quote.
    assert isinstance(password, str)


def test_the_template_no_longer_hand_quotes_the_placeholders():
    # The whole bug: a bare `'` around a placeholder that is filled in with a
    # value the template's author does not control. yaml_str() supplies its
    # own quoting, so the template must not add its own on top.
    text = TEMPLATE.read_text(encoding="utf-8")
    assert "'__PASSWORD_HASH__'" not in text
    assert "'__SSH_AUTHORIZED_KEY__'" not in text
    assert "__PASSWORD_HASH__" in text
    assert "__SSH_AUTHORIZED_KEY__" in text


# ==========================================================================
# 2. provision.sh's config.yaml, exercised via its own current source lines.
# ==========================================================================
def _config_yaml_snippet():
    """The exact 'write config.yaml' block out of the live provision.sh.

    Extracted by marker comment rather than by line number, so a future edit
    to the surrounding script does not silently start testing stale text.
    """
    text = PROVISION.read_text(encoding="utf-8")
    start = text.index("# --- 2. The config ---")
    end = text.index("# --- 3. The product ---")
    assert start < end
    return text[start:end]


def _run_config_snippet(tmp_path, media_root):
    """Run provision.sh's own config-writing lines in a sandbox.

    REPO_DIR is passed as an argument and MEDIA_ROOT through the real
    environment - never embedded as text into the generated script - so a
    MEDIA_ROOT containing a literal newline or quote arrives byte-for-byte,
    the same way ``RETROBOX_MEDIA_ROOT`` would reach the real script, instead
    of being mangled by however Python chose to quote it into source text.
    """
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    script = tmp_path / "run.sh"
    script.write_text(
        "#!/usr/bin/env bash\n"
        "set -euo pipefail\n"
        'REPO_DIR="$1"\n'
        'say() { echo "==> $*"; }\n'
        'die() { echo "!!  FATAL: $*" >&2; exit 1; }\n'
        + _config_yaml_snippet() + "\n",
        encoding="utf-8",
    )
    env = dict(os.environ)
    env["MEDIA_ROOT"] = media_root
    result = subprocess.run(
        ["bash", str(script), str(repo_dir)],
        env=env, capture_output=True, text=True, timeout=30,
    )
    config_path = repo_dir / "config.yaml"
    return result, (config_path.read_text(encoding="utf-8") if config_path.exists() else None)


@pytest.mark.parametrize("media_root", [
    "/media/retrobox",
    "/media/My Retro Videos",   # a space alone must still work
])
def test_an_ordinary_media_root_produces_a_config_that_parses(tmp_path, media_root):
    result, text = _run_config_snippet(tmp_path, media_root)
    assert result.returncode == 0, result.stderr
    document = yaml.safe_load(text)
    assert document["media_root"] == media_root
    assert document["channels"][0]["path"] == media_root + "/.welcome"


@pytest.mark.parametrize("media_root", [
    "/media/retro box: extra",     # colon -> unparseable mapping
    "/media/retro box # note",     # hash -> silently truncates at a comment
    "/media/it's mine",            # apostrophe -> breaks a single-quoted scalar
    "/media/weird\nauto_channels: false",  # newline -> injects a document line
])
def test_a_media_root_that_would_corrupt_the_yaml_is_refused_not_written(tmp_path, media_root):
    result, text = _run_config_snippet(tmp_path, media_root)
    assert result.returncode != 0, (
        f"provision.sh accepted a dangerous MEDIA_ROOT and produced:\n{text}"
    )
    assert text is None, "a rejected MEDIA_ROOT must not leave a config.yaml behind"


def test_provision_sh_single_quotes_both_media_root_scalars():
    # Static guard alongside the behavioural ones above: both places
    # media_root is written must be inside single quotes in the source, not
    # bare interpolation.
    snippet = _config_yaml_snippet()
    assert "media_root: '${MEDIA_ROOT}'" in snippet
    assert "path: '${MEDIA_ROOT}/.welcome'" in snippet
